/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Objects.eventDetailsObject;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import libraryFunctions.*;

/**
 *
 * @author PC
 */
public class addUpcomingEvent extends javax.swing.JFrame {
    public static eventDetailsObject tempEvent;
    public addUpcomingEvent() {
        initComponents();
    }
   
    public static eventDetailsObject returnTempEvent(){
        
        return tempEvent;
    }
    public String returnName(){
        String name = tempEvent.getEventName();
        return name;
    }
    public String returnType(){
        String type = tempEvent.getEventType();
        return type;
    }
    public LocalDate returnDate(){
        LocalDate date = tempEvent.getDate();
        return date;
    }
   
    public LocalTime returnTime(){
        LocalTime time = tempEvent.getTime();
        return time;
    }
   
    public double returnPrice(){
        double price = tempEvent.getEventPrice();
        return price;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        nameEntered = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateEntered = new javax.swing.JTextField();
        timeEntered = new javax.swing.JTextField();
        typeEntered = new javax.swing.JTextField();
        priceEntered = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        musicButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sportButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Time");

        nameEntered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEnteredActionPerformed(evt);
            }
        });

        jLabel4.setText("Type");

        jLabel5.setText("Price");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        musicButton.setText("Music");
        musicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Event name");

        sportButton.setText("Sport");
        sportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(musicButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(sportButton))
                    .addComponent(nameEntered, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateEntered, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeEntered, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeEntered, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceEntered, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(timeEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(typeEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(priceEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicButton)
                    .addComponent(sportButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameEnteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEnteredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEnteredActionPerformed

    private void musicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicButtonActionPerformed
       try{
        String name = new String(nameEntered.getText());
        String dateStr = new String(dateEntered.getText());
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(dateStr, dateFormatter);
       
        String timeStr = new String(timeEntered.getText());
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH/mm");
        LocalTime time = LocalTime.parse(timeStr, timeFormatter);
     
        String type = new String(typeEntered.getText());
        String priceStr = new String(priceEntered.getText());
        double price = Float.parseFloat(priceStr);
        int eventID = databaseOrders.generateEventID();
       
       eventDetailsObject newEvent = new eventDetailsObject(eventID, name, type, date, time, price);
       tempEvent = newEvent;
        musicGUI music = new musicGUI();
                music.setVisible(true);
                this.dispose();
       }catch(Exception e){
           System.out.println("Try again. "+e);
       }
    }//GEN-LAST:event_musicButtonActionPerformed

    private void sportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportButtonActionPerformed
      try{
        String name = new String(nameEntered.getText());
        String dateStr = new String(dateEntered.getText());
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(dateStr, dateFormatter);
       
        String timeStr = new String(timeEntered.getText());
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH/mm");
        LocalTime time = LocalTime.parse(timeStr, timeFormatter);
     
        String type = new String(typeEntered.getText());
        String priceStr = new String(priceEntered.getText());
        double price = Float.parseFloat(priceStr);
        int eventID = databaseOrders.generateEventID();
       
       eventDetailsObject newEvent = new eventDetailsObject(eventID, name, type, date, time, price);
       tempEvent = newEvent;
        sportGUI sport = new sportGUI();
                sport.setVisible(true);
                this.dispose();
                }catch(Exception e){
           System.out.println("Try again. "+e);
       }
    }//GEN-LAST:event_sportButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        adminHome home = new adminHome();
                home.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUpcomingEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUpcomingEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUpcomingEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUpcomingEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUpcomingEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateEntered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton musicButton;
    private javax.swing.JTextField nameEntered;
    private javax.swing.JTextField priceEntered;
    private javax.swing.JButton sportButton;
    private javax.swing.JTextField timeEntered;
    private javax.swing.JTextField typeEntered;
    // End of variables declaration//GEN-END:variables
}
